---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
  namespace: default
  labels:
    app: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
      - name: app
        image: 192.168.0.30:20000/bastion:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home
          name: home
        ports:
          - name: ssh
            containerPort: 22
          - name: mosh-60000
            containerPort: 60000
          - name: mosh-60001
            containerPort: 60001
          - name: mosh-60002
            containerPort: 60002
          - name: mosh-60003
            containerPort: 60003
          - name: mosh-60004
            containerPort: 60004
          - name: mosh-60005
            containerPort: 60005
          - name: mosh-60006
            containerPort: 60006
          - name: mosh-60007
            containerPort: 60007
          - name: mosh-60008
            containerPort: 60008
          - name: mosh-60009
            containerPort: 60009
          - name: mosh-60010
            containerPort: 60010
          - name: mosh-60011
            containerPort: 60011
          - name: mosh-60012
            containerPort: 60012
          - name: mosh-60013
            containerPort: 60013
          - name: mosh-60014
            containerPort: 60014
          - name: mosh-60015
            containerPort: 60015
          - name: mosh-60016
            containerPort: 60016
          - name: mosh-60017
            containerPort: 60017
          - name: mosh-60018
            containerPort: 60018
          - name: mosh-60019
            containerPort: 60019
          - name: mosh-60020
            containerPort: 60020
          - name: mosh-60021
            containerPort: 60021
          - name: mosh-60022
            containerPort: 60022
          - name: mosh-60023
            containerPort: 60023
          - name: mosh-60024
            containerPort: 60024
          - name: mosh-60025
            containerPort: 60025
          - name: mosh-60026
            containerPort: 60026
          - name: mosh-60027
            containerPort: 60027
          - name: mosh-60028
            containerPort: 60028
          - name: mosh-60029
            containerPort: 60029
          - name: mosh-60030
            containerPort: 60030
          - name: mosh-60031
            containerPort: 60031
          - name: mosh-60032
            containerPort: 60032
          - name: mosh-60033
            containerPort: 60033
          - name: mosh-60034
            containerPort: 60034
          - name: mosh-60035
            containerPort: 60035
          - name: mosh-60036
            containerPort: 60036
          - name: mosh-60037
            containerPort: 60037
          - name: mosh-60038
            containerPort: 60038
          - name: mosh-60039
            containerPort: 60039
          - name: mosh-60040
            containerPort: 60040
          - name: mosh-60041
            containerPort: 60041
          - name: mosh-60042
            containerPort: 60042
          - name: mosh-60043
            containerPort: 60043
          - name: mosh-60044
            containerPort: 60044
          - name: mosh-60045
            containerPort: 60045
          - name: mosh-60046
            containerPort: 60046
          - name: mosh-60047
            containerPort: 60047
          - name: mosh-60048
            containerPort: 60048
          - name: mosh-60049
            containerPort: 60049
          - name: mosh-60050
            containerPort: 60050
          - name: mosh-60051
            containerPort: 60051
          - name: mosh-60052
            containerPort: 60052
          - name: mosh-60053
            containerPort: 60053
          - name: mosh-60054
            containerPort: 60054
          - name: mosh-60055
            containerPort: 60055
          - name: mosh-60056
            containerPort: 60056
          - name: mosh-60057
            containerPort: 60057
          - name: mosh-60058
            containerPort: 60058
          - name: mosh-60059
            containerPort: 60059
          - name: mosh-60060
            containerPort: 60060
          - name: mosh-60061
            containerPort: 60061
          - name: mosh-60062
            containerPort: 60062
          - name: mosh-60063
            containerPort: 60063
          - name: mosh-60064
            containerPort: 60064
          - name: mosh-60065
            containerPort: 60065
          - name: mosh-60066
            containerPort: 60066
          - name: mosh-60067
            containerPort: 60067
          - name: mosh-60068
            containerPort: 60068
          - name: mosh-60069
            containerPort: 60069
          - name: mosh-60070
            containerPort: 60070
          - name: mosh-60071
            containerPort: 60071
          - name: mosh-60072
            containerPort: 60072
          - name: mosh-60073
            containerPort: 60073
          - name: mosh-60074
            containerPort: 60074
          - name: mosh-60075
            containerPort: 60075
          - name: mosh-60076
            containerPort: 60076
          - name: mosh-60077
            containerPort: 60077
          - name: mosh-60078
            containerPort: 60078
          - name: mosh-60079
            containerPort: 60079
          - name: mosh-60080
            containerPort: 60080
          - name: mosh-60081
            containerPort: 60081
          - name: mosh-60082
            containerPort: 60082
          - name: mosh-60083
            containerPort: 60083
          - name: mosh-60084
            containerPort: 60084
          - name: mosh-60085
            containerPort: 60085
          - name: mosh-60086
            containerPort: 60086
          - name: mosh-60087
            containerPort: 60087
          - name: mosh-60088
            containerPort: 60088
          - name: mosh-60089
            containerPort: 60089
          - name: mosh-60090
            containerPort: 60090
          - name: mosh-60091
            containerPort: 60091
          - name: mosh-60092
            containerPort: 60092
          - name: mosh-60093
            containerPort: 60093
          - name: mosh-60094
            containerPort: 60094
          - name: mosh-60095
            containerPort: 60095
          - name: mosh-60096
            containerPort: 60096
          - name: mosh-60097
            containerPort: 60097
          - name: mosh-60098
            containerPort: 60098
          - name: mosh-60099
            containerPort: 60099
          - name: mosh-60100
            containerPort: 60100
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: home
---
kind: Service
apiVersion: v1
metadata:
  name: bastion
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bastion
  ports:
    - protocol: TCP
      port: 2200
      targetPort: 22
      name: ssh
---
kind: Service
apiVersion: v1
metadata:
  name: bastion-mosh
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: bastion
  ports:
    - protocol: UDP
      port: 60000
      name: bastion-60000
    - protocol: UDP
      port: 60001
      name: bastion-60001
    - protocol: UDP
      port: 60002
      name: bastion-60002
    - protocol: UDP
      port: 60003
      name: bastion-60003
    - protocol: UDP
      port: 60004
      targetPort: 60004
      name: bastion-60004
    - protocol: UDP
      port: 60005
      targetPort: 60005
      name: bastion-60005
    - protocol: UDP
      port: 60006
      targetPort: 60006
      name: bastion-60006
    - protocol: UDP
      port: 60007
      targetPort: 60007
      name: bastion-60007
    - protocol: UDP
      port: 60008
      targetPort: 60008
      name: bastion-60008
    - protocol: UDP
      port: 60009
      targetPort: 60009
      name: bastion-60009
    - protocol: UDP
      port: 60010
      targetPort: 60010
      name: bastion-60010
    - protocol: UDP
      port: 60011
      targetPort: 60011
      name: bastion-60011
    - protocol: UDP
      port: 60012
      targetPort: 60012
      name: bastion-60012
    - protocol: UDP
      port: 60013
      targetPort: 60013
      name: bastion-60013
    - protocol: UDP
      port: 60014
      targetPort: 60014
      name: bastion-60014
    - protocol: UDP
      port: 60015
      targetPort: 60015
      name: bastion-60015
    - protocol: UDP
      port: 60016
      targetPort: 60016
      name: bastion-60016
    - protocol: UDP
      port: 60017
      targetPort: 60017
      name: bastion-60017
    - protocol: UDP
      port: 60018
      targetPort: 60018
      name: bastion-60018
    - protocol: UDP
      port: 60019
      targetPort: 60019
      name: bastion-60019
    - protocol: UDP
      port: 60020
      targetPort: 60020
      name: bastion-60020
    - protocol: UDP
      port: 60021
      targetPort: 60021
      name: bastion-60021
    - protocol: UDP
      port: 60022
      targetPort: 60022
      name: bastion-60022
    - protocol: UDP
      port: 60023
      targetPort: 60023
      name: bastion-60023
    - protocol: UDP
      port: 60024
      targetPort: 60024
      name: bastion-60024
    - protocol: UDP
      port: 60025
      targetPort: 60025
      name: bastion-60025
    - protocol: UDP
      port: 60026
      targetPort: 60026
      name: bastion-60026
    - protocol: UDP
      port: 60027
      targetPort: 60027
      name: bastion-60027
    - protocol: UDP
      port: 60028
      targetPort: 60028
      name: bastion-60028
    - protocol: UDP
      port: 60029
      targetPort: 60029
      name: bastion-60029
    - protocol: UDP
      port: 60030
      targetPort: 60030
      name: bastion-60030
    - protocol: UDP
      port: 60031
      targetPort: 60031
      name: bastion-60031
    - protocol: UDP
      port: 60032
      targetPort: 60032
      name: bastion-60032
    - protocol: UDP
      port: 60033
      targetPort: 60033
      name: bastion-60033
    - protocol: UDP
      port: 60034
      targetPort: 60034
      name: bastion-60034
    - protocol: UDP
      port: 60035
      targetPort: 60035
      name: bastion-60035
    - protocol: UDP
      port: 60036
      targetPort: 60036
      name: bastion-60036
    - protocol: UDP
      port: 60037
      targetPort: 60037
      name: bastion-60037
    - protocol: UDP
      port: 60038
      targetPort: 60038
      name: bastion-60038
    - protocol: UDP
      port: 60039
      targetPort: 60039
      name: bastion-60039
    - protocol: UDP
      port: 60040
      targetPort: 60040
      name: bastion-60040
    - protocol: UDP
      port: 60041
      targetPort: 60041
      name: bastion-60041
    - protocol: UDP
      port: 60042
      targetPort: 60042
      name: bastion-60042
    - protocol: UDP
      port: 60043
      targetPort: 60043
      name: bastion-60043
    - protocol: UDP
      port: 60044
      targetPort: 60044
      name: bastion-60044
    - protocol: UDP
      port: 60045
      targetPort: 60045
      name: bastion-60045
    - protocol: UDP
      port: 60046
      targetPort: 60046
      name: bastion-60046
    - protocol: UDP
      port: 60047
      targetPort: 60047
      name: bastion-60047
    - protocol: UDP
      port: 60048
      targetPort: 60048
      name: bastion-60048
    - protocol: UDP
      port: 60049
      targetPort: 60049
      name: bastion-60049
    - protocol: UDP
      port: 60050
      targetPort: 60050
      name: bastion-60050
    - protocol: UDP
      port: 60051
      targetPort: 60051
      name: bastion-60051
    - protocol: UDP
      port: 60052
      targetPort: 60052
      name: bastion-60052
    - protocol: UDP
      port: 60053
      targetPort: 60053
      name: bastion-60053
    - protocol: UDP
      port: 60054
      targetPort: 60054
      name: bastion-60054
    - protocol: UDP
      port: 60055
      targetPort: 60055
      name: bastion-60055
    - protocol: UDP
      port: 60056
      targetPort: 60056
      name: bastion-60056
    - protocol: UDP
      port: 60057
      targetPort: 60057
      name: bastion-60057
    - protocol: UDP
      port: 60058
      targetPort: 60058
      name: bastion-60058
    - protocol: UDP
      port: 60059
      targetPort: 60059
      name: bastion-60059
    - protocol: UDP
      port: 60060
      targetPort: 60060
      name: bastion-60060
    - protocol: UDP
      port: 60061
      targetPort: 60061
      name: bastion-60061
    - protocol: UDP
      port: 60062
      targetPort: 60062
      name: bastion-60062
    - protocol: UDP
      port: 60063
      targetPort: 60063
      name: bastion-60063
    - protocol: UDP
      port: 60064
      targetPort: 60064
      name: bastion-60064
    - protocol: UDP
      port: 60065
      targetPort: 60065
      name: bastion-60065
    - protocol: UDP
      port: 60066
      targetPort: 60066
      name: bastion-60066
    - protocol: UDP
      port: 60067
      targetPort: 60067
      name: bastion-60067
    - protocol: UDP
      port: 60068
      targetPort: 60068
      name: bastion-60068
    - protocol: UDP
      port: 60069
      targetPort: 60069
      name: bastion-60069
    - protocol: UDP
      port: 60070
      targetPort: 60070
      name: bastion-60070
    - protocol: UDP
      port: 60071
      targetPort: 60071
      name: bastion-60071
    - protocol: UDP
      port: 60072
      targetPort: 60072
      name: bastion-60072
    - protocol: UDP
      port: 60073
      targetPort: 60073
      name: bastion-60073
    - protocol: UDP
      port: 60074
      targetPort: 60074
      name: bastion-60074
    - protocol: UDP
      port: 60075
      targetPort: 60075
      name: bastion-60075
    - protocol: UDP
      port: 60076
      targetPort: 60076
      name: bastion-60076
    - protocol: UDP
      port: 60077
      targetPort: 60077
      name: bastion-60077
    - protocol: UDP
      port: 60078
      targetPort: 60078
      name: bastion-60078
    - protocol: UDP
      port: 60079
      targetPort: 60079
      name: bastion-60079
    - protocol: UDP
      port: 60080
      targetPort: 60080
      name: bastion-60080
    - protocol: UDP
      port: 60081
      targetPort: 60081
      name: bastion-60081
    - protocol: UDP
      port: 60082
      targetPort: 60082
      name: bastion-60082
    - protocol: UDP
      port: 60083
      targetPort: 60083
      name: bastion-60083
    - protocol: UDP
      port: 60084
      targetPort: 60084
      name: bastion-60084
    - protocol: UDP
      port: 60085
      targetPort: 60085
      name: bastion-60085
    - protocol: UDP
      port: 60086
      targetPort: 60086
      name: bastion-60086
    - protocol: UDP
      port: 60087
      targetPort: 60087
      name: bastion-60087
    - protocol: UDP
      port: 60088
      targetPort: 60088
      name: bastion-60088
    - protocol: UDP
      port: 60089
      targetPort: 60089
      name: bastion-60089
    - protocol: UDP
      port: 60090
      targetPort: 60090
      name: bastion-60090
    - protocol: UDP
      port: 60091
      targetPort: 60091
      name: bastion-60091
    - protocol: UDP
      port: 60092
      targetPort: 60092
      name: bastion-60092
    - protocol: UDP
      port: 60093
      targetPort: 60093
      name: bastion-60093
    - protocol: UDP
      port: 60094
      targetPort: 60094
      name: bastion-60094
    - protocol: UDP
      port: 60095
      targetPort: 60095
      name: bastion-60095
    - protocol: UDP
      port: 60096
      targetPort: 60096
      name: bastion-60096
    - protocol: UDP
      port: 60097
      targetPort: 60097
      name: bastion-60097
    - protocol: UDP
      port: 60098
      targetPort: 60098
      name: bastion-60098
    - protocol: UDP
      port: 60099
      targetPort: 60099
      name: bastion-60099
    - protocol: UDP
      port: 60100
      targetPort: 60100
      name: bastion-60100
