apiVersion: v1
kind: PersistentVolume
metadata:
  name: home
  namespace: default
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.30
    path: "/volume1/bastionhome"
